import type { NodeDefinition } from "@/types/workflow";

export const NODE_DEFINITIONS: NodeDefinition[] = [
  {
    type: "textNode",
    label: "Text",
    description: "A simple text input",
    icon: "Type",
    defaultData: { text: "" },
    inputs: [],
    outputs: [{ id: "output-text", label: "text", dataType: "text" }],
  },
  {
    type: "uploadImageNode",
    label: "Upload Image",
    description: "Upload an image file",
    icon: "Image",
    defaultData: { imageUrl: null, uploadProgress: 0, fileName: null },
    inputs: [],
    outputs: [{ id: "output-image_url", label: "image_url", dataType: "image" }],
  },
  {
    type: "uploadVideoNode",
    label: "Upload Video",
    description: "Upload a video file",
    icon: "Video",
    defaultData: { videoUrl: null, uploadProgress: 0, fileName: null },
    inputs: [],
    outputs: [{ id: "output-video_url", label: "video_url", dataType: "video" }],
  },
  {
    type: "runLLMNode",
    label: "Run LLM",
    description: "Run a Gemini language model",
    icon: "Sparkles",
    defaultData: {
      model: "gemini-2.0-flash",
      systemPrompt: "",
      userMessage: "",
      systemPromptConnected: false,
      userMessageConnected: false,
      imagesConnected: false,
      result: null,
    },
    inputs: [
      { id: "input-system_prompt", label: "system_prompt", dataType: "text", required: false },
      { id: "input-user_message", label: "user_message", dataType: "text", required: true },
      { id: "input-images", label: "images", dataType: "image", required: false },
    ],
    outputs: [{ id: "output-output", label: "output", dataType: "text" }],
  },
  {
    type: "cropImageNode",
    label: "Crop Image",
    description: "Crop an image by percentage",
    icon: "Crop",
    defaultData: {
      imageUrlConnected: false,
      xPercent: 0,
      yPercent: 0,
      widthPercent: 100,
      heightPercent: 100,
      xPercentConnected: false,
      yPercentConnected: false,
      widthPercentConnected: false,
      heightPercentConnected: false,
      outputUrl: null,
    },
    inputs: [
      { id: "input-image_url", label: "image_url", dataType: "image", required: true },
      { id: "input-x_percent", label: "x_percent", dataType: "number", required: false },
      { id: "input-y_percent", label: "y_percent", dataType: "number", required: false },
      { id: "input-width_percent", label: "width_percent", dataType: "number", required: false },
      { id: "input-height_percent", label: "height_percent", dataType: "number", required: false },
    ],
    outputs: [{ id: "output-output", label: "output", dataType: "image" }],
  },
  {
    type: "extractFrameNode",
    label: "Extract Frame",
    description: "Extract a frame from video",
    icon: "Film",
    defaultData: {
      videoUrlConnected: false,
      timestamp: "0",
      timestampConnected: false,
      outputUrl: null,
    },
    inputs: [
      { id: "input-video_url", label: "video_url", dataType: "video", required: true },
      { id: "input-timestamp", label: "timestamp", dataType: "text", required: false },
    ],
    outputs: [{ id: "output-output", label: "output", dataType: "image" }],
  },
];
